projectId: app-ywifFuW43gXf7MKTzQKepF
appName: bunnyhops
description: This is a sample app description
imageURL: Nope
version: 1.0.0
hostName: example.test
clusterURL: https://kubernetes.default.svc
clusterIPs:
- 800.800.900
- 790.890.789
monitoring: true
microservices:
  CartService:
    serviceName: cartservice
    dockerImage: "1"
  OrderService:
    serviceName: orderservice
    dockerImage: "1"
    serviceEvaluation:
      kubeConfigType:
      - statefulSetBased
  UserService:
    serviceName: userservice
    dockerImage: "1"
evaluationResult:
  language: Java
  database: MySQL
  microservices:
  - CartService
  - OrderService
  - UserService
